; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
framework = arduino
board = esp32thing
board_build.mcu = esp32
build_flags =
    -D NFC_INTERFACE_SPI
    -D HAVE_ED25519_KEY_EXPORT -D HAVE_ED25519 -D WOLFSSL_SHA512 -D HAVE_HPKE
    -D HAVE_HKDF -D WOLFSSL_KEY_GEN -D HAVE_CURVE25519
    -D WOLFSSL_CLIENT_EXAMPLE -D NO_WOLFSSL_CLIENT
    -D WC_NO_HARDEN
    ; -D WOLFSSL_ESP32 -D WOLFSSL_SHA512 -D WOLFSSL_ESP32_CRYPT -D CONFIG_IDF_TARGET_ESP32
    ; -D DEBUG
lib_deps =
    https://github.com/Seeed-Studio/PN532.git
    wolfssl/Arduino-wolfSSL
    https://github.com/sstaub/NTP3.git
upload_port = /dev/tty.usbserial-DN0280BY
monitor_port = /dev/tty.usbserial-DN0280BY
monitor_speed = 115200
debug_tool = jlink
; debug_init_break = tbreak setup
